arbre_decision:
  config_vide: false
  longueur_arbre:
  - 1
  - 3
  - 5
  - 7
  nombre_noeuds:
  - 2
  - 4
  - 6
  parametre_complexite:
  - 0.0
  - 1.0
  - 2.0
bayesien:
  alpha:
  - 0.001
  - 0.01
  - 0.1
  - 1.0
  config_vide: false
benet:
  config_vide: false
  strategies:
  - prior
  - stratified
  - uniform
foret:
  config_vide: false
  longueur_arbre:
  - 1
  - 5
  - 10
  - 25
  nombre_estimateurs:
  - 10
  - 100
  - 250
  - 400
k_voisins:
  config_vide: false
  nombre_voisins:
  - 1
  - 5
  - 11
  - 20
  type_distance:
  - 1
  - 2
neurones:
  alpha:
  - 0.001
  - 0.1
  architecture:
  - - 100
  - - 50
    - 50
  config_vide: false
  max_iter:
  - 500
  - 1000
  - 10000
support_vecteurs:
  config_vide: false
  regularisation:
  - 0.1
  - 1.0
  - 5.0
